INSERT INTO INVENTORY (ID, PRODUCT_CODE, AVAILABLE) VALUES (1, 'COMIC_BOOKS', 600);
INSERT INTO INVENTORY (ID, PRODUCT_CODE, AVAILABLE) VALUES (2, 'BOOKS', 600);
INSERT INTO INVENTORY (ID, PRODUCT_CODE, AVAILABLE) VALUES (3, 'MOVIES', 600);
INSERT INTO INVENTORY (ID, PRODUCT_CODE, AVAILABLE) VALUES (4, 'MUSIC', 600);