INSERT INTO INVENTORY (ID, PRODUCT_CODE, AVAILABLE)
VALUES (1, 'COMIC_BOOKS', 600)
ON CONFLICT (ID) DO NOTHING;
INSERT INTO INVENTORY (ID, PRODUCT_CODE, AVAILABLE)
VALUES (2, 'BOOKS', 900)
ON CONFLICT (ID) DO NOTHING;
INSERT INTO INVENTORY (ID, PRODUCT_CODE, AVAILABLE)
VALUES (3, 'MOVIES', 100)
ON CONFLICT (ID) DO NOTHING;
INSERT INTO INVENTORY (ID, PRODUCT_CODE, AVAILABLE)
VALUES (4, 'MUSIC', 1000)
ON CONFLICT (ID) DO NOTHING;